# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('orderRefNumber', models.IntegerField()),
            ],
        ),
    ]
